# https://fabricmc.net/develop/
deps.yarn_build=2
deps.fabric_api=0.87.2+1.19.4

mod.mc_title=1.19.4-1.20.4
mod.mc_dep=>=1.19.4 <=1.20.4
mod.mc_targets=1.19.4 1.20.1 1.20.2 1.20.3 1.20.4
mod.publish=false

# https://modrinth.com/mod/litematica/versions
deps.litematica=0.14.2
deps.litematica_range=>=0.14.2 <=0.17.4

# https://modrinth.com/mod/malilib/versions
deps.malilib=0.15.2
deps.malilib_range=>=0.15.2 <=0.18.3