# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

# The version on version control
settings.vcsVersion=dev
# An unpublished version that can be used to prepare for upcoming releases
settings.devVersion=1.21.9
# A comma separated list of all published versions
settings.versions=1.21.5, 1.20.6, 1.19.4

# Mod properties
mod.version=1.0.0
mod.group=com.scubakay
mod.id=litematica-enderchest-materials
mod.name=Litematica Enderchest Materials

# for fabric.mod.json
mod.mc_dep=[VERSIONED]
# for release title
mod.mc_title=[VERSIONED]
# for release metadata
mod.mc_targets=[VERSIONED]
# Publish or not
mod.publish=[VERSIONED]

# Global dependencies
deps.fabric_loader=0.17.2

deps.litematica=[VERSIONED]
deps.malilib=[VERSIONED]

# Publishing
publish.modrinth=oBzw5QUs
publish.curseforge=...