# https://fabricmc.net/develop/
deps.yarn_build=1
deps.fabric_api=0.97.8+1.20.5

mod.mc_title=0.18.0-0.21.4
mod.mc_version=1.20.5
mod.mc_dep=>=1.20.5 <=1.21.4
mod.mc_targets=1.20.5 1.20.6 1.21 1.21.1 1.21.2 1.21.3 1.21.4
mod.publish=false

# https://modrinth.com/mod/litematica/versions
deps.litematica=0.18.0
deps.litematica_range=>=0.18.0 <=0.21.4

# https://modrinth.com/mod/malilib/versions
deps.malilib=0.19.0
deps.malilib_range=>=0.19.0 <=0.23.4