# https://fabricmc.net/develop/
deps.yarn_build=1
deps.fabric_api=0.133.14+1.21.9

mod.mc_title=dev
mod.mc_dep=1.21.9
mod.mc_targets=1.21.9
mod.publish=false

# https://modrinth.com/mod/litematica/versions
deps.litematica=0.24.0
deps.litematica_range=>=0.22.0

# https://modrinth.com/mod/malilib/versions
deps.malilib=0.26.1
deps.malilib_range=>=0.24.0