# https://fabricmc.net/develop/
deps.yarn_build=4
deps.fabric_api=0.141.1+1.21.11

mod.mc_title=dev
mod.mc_dep=1.21.11
mod.mc_targets=1.21.11
mod.publish=false

# https://modrinth.com/mod/litematica/versions
deps.litematica=0.25.3
deps.litematica_range=>=0.22.0

# https://modrinth.com/mod/malilib/versions
deps.malilib=0.27.2
deps.malilib_range=>=0.24.0