# https://fabricmc.net/develop/
deps.yarn_build=1
deps.fabric_api=0.121.0+1.21.5

mod.mc_title=0.22.0-0.24.0
mod.mc_version=1.21.5
mod.mc_dep=>=1.21.5 <=1.21.9
mod.mc_targets=1.21.5 1.21.6 1.21.7 1.21.8 1.21.9
mod.publish=false

# https://modrinth.com/mod/litematica/versions
deps.litematica=0.22.0
deps.litematica_range=>=0.22.0 <=0.24.0

# https://modrinth.com/mod/malilib/versions
deps.malilib=0.24.0
deps.malilib_range=>=0.24.0 <=0.26.1