name: Create release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  JAVA_VERSION: 21
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  #  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "${{env.JAVA_VERSION}}"
          distribution: 'temurin'

      - name: Build
        run: ./gradlew clean build

      - name: Publish Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog-file: CHANGELOG.md
          java: "${{env.JAVA_VERSION}}"

          modrinth-id: oBzw5QUs
          modrinth-token: "${{env.MODRINTH_TOKEN}}"