# https://fabricmc.net/develop/
deps.yarn_build=9
deps.fabric_api=0.102.0+1.21

mod.mc_title=0.19.52-0.21.4
mod.mc_version=1.21
mod.mc_dep=>=1.21 <=1.21.4
mod.mc_targets=1.21 1.21.1 1.21.2 1.21.3 1.21.4
mod.publish=false

# https://modrinth.com/mod/litematica/versions
deps.litematica=0.19.52
deps.litematica_range=>=0.19.52 <=0.21.4

# https://modrinth.com/mod/malilib/versions
deps.malilib=0.21.9
deps.malilib_range=>=0.20.0 <=0.23.4